### ISSUE TITLE
Reconnect didn't add "online" log record. Availability stats incorrect calculated

### ISSUE THREAD

**Issue by MarcoSchermers** [dmishh/internet-connection-monitor-website#10]
See screenshot. I lost internet connection at 7:56;21 AM. Shortly after the internet connection was restored. No entry is added to the log that the internet connection was restored. Also the  availability stats are incorrect calculated, because of this missing log entry.

At 11:43:34 AM the General Stats section states that there is a connection for 3:47:12. Is means that at 7:56:22 AM connection was restored. There is not online entry in the log. 
When you look back for the last 24 hours for there was no connection for 9 + 10 + 1 = 20 seconds. However, the General Stats suggest that there was only availability 84,20%. This is not correct calculated. 

![Internet_Connection_Monitor_2021-06-07 11_43_33](https://user-images.githubusercontent.com/76482178/120995708-f0d4fc80-c785-11eb-917d-de10afc56ffb.jpg)

**Comment by dmishh** [comment]
@MarcoSchermers cool, thanks for the info. I hope this issue won't happen again. But if it is - feel free to report a new ticket.
Also, there is a new feature available - custom testing interval. You can choose from every 1 to 5 seconds. It may help you to track the annoying outages and show the stats to your ISP.
