### ISSUE TITLE
Internet connection improvements recommendation page

### ISSUE THREAD

**Issue by dmishh** [dmishh/internet-connection-monitor-website#36]
Add a separate page or popup to show recommendations on improving Internet connection

- [x] Router
- [x] VPN
- [x] Add a recommendations page to the website

**Comment by gpcdad** [comment]
Great to have this tool available! Thank you for your work!

I would like to know if you have plans to add notifications when the internet connection has issues based on disconnects, latency.

Thank you

**Comment by dmishh** [comment]
@gpcdad that's a good idea, thanks! I'll track your request here - https://github.com/dmishh/internet-connection-monitor-website/issues/40

You're referring to Chrome OS-native notifications, right?
